//
//  WrapperServiceMediator.h
//  ZOLWallWrapper
//
//  Created by zhujinhui on 14-12-27.
//  Copyright (c) 2014年 zhujinhui. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "ServiceMediator.h"

#define HOST_PICSHOW @"http://app.zol.com.cn/bizhi"

#define SERVICENAME_RECOMMENDEDLIST     @"SERVICENAME_RECOMMENDEDLIST"
#define SERVICENAME_RECOMMENDEDDETAIL   @"SERVICENAME_RECOMMENDEDDETAIL"
#define SERVICENAME_LATESTLIST          @"SERVICENAME_LATESTLIST"
#define SERVICENAME_CATEGORYLIST        @"SERVICENAME_CATEGORYLIST"
//category
#define SERVICENAME_CATEGORYRECOMMENDEDLIST         @"SERVICENAME_CATEGORYRECOMMENDEDLIST"
#define SERVICENAME_CATEGORYHOTESTLIST              @"SERVICENAME_CATEGORYHOTESTLIST"
#define SERVICENAME_CATEGORYLATESTLIST              @"SERVICENAME_CATEGORYLATESTLIST"
//second category
#define SERVICENAME_CATEGORYSECONDARY           @"SERVICENAME_CATEGORYSECONDARY"

#define SERVICENAME_SECONDARYCATEGORYRECOMMENDEDLIST         @"SERVICENAME_SECONDARYCATEGORYRECOMMENDEDLIST"
#define SERVICENAME_SECONDARYCATEGORYHOTESTLIST              @"SERVICENAME_SECONDARYCATEGORYHOTESTLIST"
#define SERVICENAME_SECONDARYCATEGORYLATESTLIST              @"SERVICENAME_SECONDARYCATEGORYLATESTLIST"


#define SERVICENAME_SEARCHGETSEARCHRESULTLIST              @"SERVICENAME_SEARCHGETSEARCHRESULTLIST"




@interface WrapperServiceMediator : ServiceMediator

@end
